version: 0.0
os: windows
files:
  - source: \
    destination: C:\Users\Administrator\Desktop\build_release
hooks:
  BeforeInstall:
    - location: stopApp.ps1 
  AfterInstall:
    - location: moveFiles.bat   
  ApplicationStart:
    - location: installApp.ps1
      timeout: 300