version: 0.2
phases:
  pre_build:
    commands:
      - dotnet restore ./demoapp/demoapp.csproj
  build:
    commands:
      - dotnet publish ./demoapp/demoapp.csproj -o ./demoapp/build_artifacts --configuration Release
  post-build:
    commands:
      - mv build_artifacts/**/* ./
      - mv build_artifacts/* ./
      - rm -R build-output    
artifacts:
  files:
    - demoapp/build_artifacts/**/*
    - demoapp/wwwroot/**/*
    - installApp.ps1
    - stopApp.ps1
    - appspec.yml