version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore ./demoapp/demoapp.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./demoapp/build_output demoapp.csproj
artifacts:
  files:
    - demoapp/bin/netcoreapp3.1
    - demoapp/wwwroot/**/*