version: 0.2
phases:
pre_build:
commands:
- echo Restore started on `date`
- dotnet restore demoapp.csproj
build:
commands:
- echo Build started on `date`
- dotnet publish -c release -o ./build_output demoapp.csproj
artifacts:
files:
- demoapp/build_output/**/*
- wwwroot/**/*