version: 0.2
phases:
  pre_build:
    commands:
      - dotnet restore ./demoapp/demoapp.csproj
  build:
    commands:
      - dotnet publish ./demoapp/demoapp.csproj -o ./demoapp/build_artifacts --configuration Release --framework netcoreapp3.1
artifacts:
  files:
    - demoapp/build_artifacts/**/*
    - installApp.ps1
    - stopApp.ps1
    - moveFiles.ps1
    - appspec.yml